/* https://leetcode.com/problems/find-the-difference/
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
*/

var findTheDifference = function(s, t) {
  const lettersSeen = {};

  // add letters for t string to hash table
  for (let i = 0; i < t.length; i++) {
    let newStrChar = t[i];

    if (!lettersSeen[newStrChar]) {
      lettersSeen[newStrChar] = 0;
    }
    lettersSeen[newStrChar]++;
  }

  // compare letters in s string to hash table & decrease value
  // for each time seen
  for (let i = 0; i < s.length; i++) {
    let oldStrChar = s[i];
    if (lettersSeen[oldStrChar]) {
      lettersSeen[oldStrChar]--;
    }
  }

  const letters = Object.keys(lettersSeen);

  for (let i = 0; i < letters.length; i++) {
    let differentLetter = letters[i];
    if (lettersSeen[differentLetter] === 1) return differentLetter;
  }
};
